require 'faker'
prng = Random.new
products = Product.all
users = User.all

## *****************************************************************************************************
##    PRODUCTS
## *****************************************************************************************************
    products_data = [
      {"id"=>22290213,"name"=>"The North Face Vault backpack in black","price"=>{"current"=>{"value"=>59.0,"text"=>"$59.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387315,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864198,"productType"=>"Product","url"=>"the-north-face/the-north-face-vault-backpack-in-black/prd/22290213?colourwayid=60387315","imageUrl"=>"http://images.asos-media.com/products/the-north-face-vault-backpack-in-black/22290213-1-tnfblkhrtnfblu","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21674050,"name"=>"The North Face Base Camp Small travel cannister in yellow","price"=>{"current"=>{"value"=>38.0,"text"=>"$38.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60186490,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1818634,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-small-travel-cannister-in-yellow/prd/21674050?colourwayid=60186490","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-small-travel-cannister-in-yellow/21674050-1-summitgold","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22429198,"name"=>"Nike Training Elemental logo backpack in black","price"=>{"current"=>{"value"=>47.25,"text"=>"$47.25"},"previous"=>{"value"=>63.0,"text"=>"$63.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60397541,"brandName"=>"Nike Training","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1873389,"productType"=>"Product","url"=>"nike-training/nike-training-elemental-logo-backpack-in-black/prd/22429198?colourwayid=60397541","imageUrl"=>"http://images.asos-media.com/products/nike-training-elemental-logo-backpack-in-black/22429198-1-black","videoUrl"=>"","isSellingFast"=>true},
      {"id"=>21674041,"name"=>"The North Face Base Camp Small travel cannister in purple","price"=>{"current"=>{"value"=>38.0,"text"=>"$38.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60186486,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1818631,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-small-travel-cannister-in-purple/prd/21674041?colourwayid=60186486","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-small-travel-cannister-in-purple/21674041-1-peakpurple","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22290219,"name"=>"The North Face Recon backpack in black","price"=>{"current"=>{"value"=>84.15,"text"=>"$84.15"},"previous"=>{"value"=>99.0,"text"=>"$99.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387303,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864168,"productType"=>"Product","url"=>"the-north-face/the-north-face-recon-backpack-in-black/prd/22290219?colourwayid=60387303","imageUrl"=>"http://images.asos-media.com/products/the-north-face-recon-backpack-in-black/22290219-1-tnfblack","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21315685,"name"=>"The North Face Explore Utility tote bag in brown","price"=>{"current"=>{"value"=>69.0,"text"=>"$69.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156503,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789660,"productType"=>"Product","url"=>"the-north-face/the-north-face-explore-utility-tote-bag-in-brown/prd/21315685?colourwayid=60156503","imageUrl"=>"http://images.asos-media.com/products/the-north-face-explore-utility-tote-bag-in-brown/21315685-1-utilitybrowntnfbla","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21315755,"name"=>"The North Face Explore fanny pack in yellow","price"=>{"current"=>{"value"=>30.0,"text"=>"$30.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156549,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789665,"productType"=>"Product","url"=>"the-north-face/the-north-face-explore-fanny-pack-in-yellow/prd/21315755?colourwayid=60156549","imageUrl"=>"http://images.asos-media.com/products/the-north-face-explore-fanny-pack-in-yellow/21315755-1-summitgoldtnfblack","videoUrl"=>"","isSellingFast"=>true},
      {"id"=>21315762,"name"=>"The North Face Explore fanny pack in green","price"=>{"current"=>{"value"=>30.0,"text"=>"$30.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156518,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789667,"productType"=>"Product","url"=>"the-north-face/the-north-face-explore-fanny-pack-in-green/prd/21315762?colourwayid=60156518","imageUrl"=>"http://images.asos-media.com/products/the-north-face-explore-fanny-pack-in-green/21315762-1-evergreentnfblack","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22289490,"name"=>"The North Face Base Camp travel cannister in brown","price"=>{"current"=>{"value"=>38.0,"text"=>"$38.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387207,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864089,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-travel-cannister-in-brown/prd/22289490?colourwayid=60387207","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-travel-cannister-in-brown/22289490-1-utiltybntnfblk","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22290189,"name"=>"The North Face Vault backpack in brown","price"=>{"current"=>{"value"=>59.0,"text"=>"$59.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387281,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864199,"productType"=>"Product","url"=>"the-north-face/the-north-face-vault-backpack-in-brown/prd/22290189?colourwayid=60387281","imageUrl"=>"http://images.asos-media.com/products/the-north-face-vault-backpack-in-brown/22290189-1-timbrtntnfnavy","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22290217,"name"=>"The North Face Jester backpack in gray","price"=>{"current"=>{"value"=>55.2,"text"=>"$55.20"},"previous"=>{"value"=>69.0,"text"=>"$69.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387308,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864190,"productType"=>"Product","url"=>"the-north-face/the-north-face-jester-backpack-in-gray/prd/22290217?colourwayid=60387308","imageUrl"=>"http://images.asos-media.com/products/the-north-face-jester-backpack-in-gray/22290217-1-zncgdkhrprsnor","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22290221,"name"=>"The North Face Jester backpack in navy","price"=>{"current"=>{"value"=>69.0,"text"=>"$69.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387304,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864192,"productType"=>"Product","url"=>"the-north-face/the-north-face-jester-backpack-in-navy/prd/22290221?colourwayid=60387304","imageUrl"=>"http://images.asos-media.com/products/the-north-face-jester-backpack-in-navy/22290221-1-avtrnvylhrtnfw","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>14930109,"name"=>"The North Face Base Camp travel canister large wash bag in yellow","price"=>{"current"=>{"value"=>33.0,"text"=>"$33.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>16657782,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1680647,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-travel-canister-large-wash-bag-in-yellow/prd/14930109?colourwayid=16657782","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-travel-canister-large-wash-bag-in-yellow/14930109-1-summitgoldtnfblac","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22289486,"name"=>"The North Face Base Camp travel cannister in orange","price"=>{"current"=>{"value"=>32.3,"text"=>"$32.30"},"previous"=>{"value"=>38.0,"text"=>"$38.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387217,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864087,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-travel-cannister-in-orange/prd/22289486?colourwayid=60387217","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-travel-cannister-in-orange/22289486-1-flaretnfblack","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22429205,"name"=>"Nike Training logo holdall in black","price"=>{"current"=>{"value"=>63.0,"text"=>"$63.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60397542,"brandName"=>"Nike Training","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1873337,"productType"=>"Product","url"=>"nike-training/nike-training-logo-holdall-in-black/prd/22429205?colourwayid=60397542","imageUrl"=>"http://images.asos-media.com/products/nike-training-logo-holdall-in-black/22429205-1-black","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22429202,"name"=>"Nike Training logo side bag in black","price"=>{"current"=>{"value"=>25.6,"text"=>"$25.60"},"previous"=>{"value"=>32.0,"text"=>"$32.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60397538,"brandName"=>"Nike Training","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1873307,"productType"=>"Product","url"=>"nike-training/nike-training-logo-side-bag-in-black/prd/22429202?colourwayid=60397538","imageUrl"=>"http://images.asos-media.com/products/nike-training-logo-side-bag-in-black/22429202-1-black","videoUrl"=>"","isSellingFast"=>true},
      {"id"=>21674067,"name"=>"The North Face Bozer fanny pack in yellow","price"=>{"current"=>{"value"=>32.0,"text"=>"$32.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60186479,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1818637,"productType"=>"Product","url"=>"the-north-face/the-north-face-bozer-fanny-pack-in-yellow/prd/21674067?colourwayid=60186479","imageUrl"=>"http://images.asos-media.com/products/the-north-face-bozer-fanny-pack-in-yellow/21674067-1-summitgold","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22290209,"name"=>"The North Face Vault backpack in gray","price"=>{"current"=>{"value"=>47.2,"text"=>"$47.20"},"previous"=>{"value"=>59.0,"text"=>"$59.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387291,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864195,"productType"=>"Product","url"=>"the-north-face/the-north-face-vault-backpack-in-gray/prd/22290209?colourwayid=60387291","imageUrl"=>"http://images.asos-media.com/products/the-north-face-vault-backpack-in-gray/22290209-1-mdgydkhrtnfblk","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22290204,"name"=>"The North Face Cotton Tote bag in gray","price"=>{"current"=>{"value"=>25.0,"text"=>"$25.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387318,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864188,"productType"=>"Product","url"=>"the-north-face/the-north-face-cotton-tote-bag-in-gray/prd/22290204?colourwayid=60387318","imageUrl"=>"http://images.asos-media.com/products/the-north-face-cotton-tote-bag-in-gray/22290204-1-asphgyfxdplntpt","videoUrl"=>"video.asos-media.com/products/the-north-face-cotton-tote-bag-in-gray/22290204-catwalk-AVS","isSellingFast"=>false},
      {"id"=>21315692,"name"=>"The North Face Explore Utility tote bag in yellow","price"=>{"current"=>{"value"=>69.0,"text"=>"$69.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156509,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789661,"productType"=>"Product","url"=>"the-north-face/the-north-face-explore-utility-tote-bag-in-yellow/prd/21315692?colourwayid=60156509","imageUrl"=>"http://images.asos-media.com/products/the-north-face-explore-utility-tote-bag-in-yellow/21315692-1-summitgoldtnfblack","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21315749,"name"=>"The North Face Explore fanny pack in black","price"=>{"current"=>{"value"=>30.0,"text"=>"$30.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156520,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789666,"productType"=>"Product","url"=>"the-north-face/the-north-face-explore-fanny-pack-in-black/prd/21315749?colourwayid=60156520","imageUrl"=>"http://images.asos-media.com/products/the-north-face-explore-fanny-pack-in-black/21315749-1-tnfblacktnfwhite","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21315764,"name"=>"The North Face Bozer II fanny pack in brown","price"=>{"current"=>{"value"=>29.0,"text"=>"$29.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156546,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789669,"productType"=>"Product","url"=>"the-north-face/the-north-face-bozer-ii-fanny-pack-in-brown/prd/21315764?colourwayid=60156546","imageUrl"=>"http://images.asos-media.com/products/the-north-face-bozer-ii-fanny-pack-in-brown/21315764-1-utilitybrowntnfbla","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22290216,"name"=>"The North Face Borealis Backpack in Navy","price"=>{"current"=>{"value"=>75.65,"text"=>"$75.65"},"previous"=>{"value"=>89.0,"text"=>"$89.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387306,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864177,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-backpack-in-navy/prd/22290216?colourwayid=60387306","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-backpack-in-navy/22290216-1-avtrnavymeldgy","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>22290211,"name"=>"The North Face Borealis backpack in gray","price"=>{"current"=>{"value"=>89.0,"text"=>"$89.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60387289,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1864172,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-backpack-in-gray/prd/22290211?colourwayid=60387289","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-backpack-in-gray/22290211-1-aspgrslvrflctv","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21315760,"name"=>"The North Face Surge Backpack In Black","price"=>{"current"=>{"value"=>109.65,"text"=>"$109.65"},"previous"=>{"value"=>129.0,"text"=>"$129.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156552,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789671,"productType"=>"Product","url"=>"the-north-face/the-north-face-surge-backpack-in-black/prd/21315760?colourwayid=60156552","imageUrl"=>"http://images.asos-media.com/products/the-north-face-surge-backpack-in-black/21315760-1-tnfblack","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>14927823,"name"=>"The North Face Borealis Classic backpack in black","price"=>{"current"=>{"value"=>100.0,"text"=>"$100.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>16657489,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1680375,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-classic-backpack-in-black/prd/14927823?colourwayid=16657489","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-classic-backpack-in-black/14927823-1-tnfblackasphaltgr","videoUrl"=>"video.asos-media.com/products/the-north-face-borealis-classic-backpack-in-black/14927823-catwalk-AVS","isSellingFast"=>false},
      {"id"=>21315758,"name"=>"The North Face Jester backpack in yellow","price"=>{"current"=>{"value"=>55.2,"text"=>"$55.20"},"previous"=>{"value"=>69.0,"text"=>"$69.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156526,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789673,"productType"=>"Product","url"=>"the-north-face/the-north-face-jester-backpack-in-yellow/prd/21315758?colourwayid=60156526","imageUrl"=>"http://images.asos-media.com/products/the-north-face-jester-backpack-in-yellow/21315758-1-summitgoldtnfblack","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21356585,"name"=>"The North Face Borealis Classic backpack in green","price"=>{"current"=>{"value"=>80.0,"text"=>"$80.00"},"previous"=>{"value"=>100.0,"text"=>"$100.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60160287,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1793265,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-classic-backpack-in-green/prd/21356585?colourwayid=60160287","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-classic-backpack-in-green/21356585-1-newtaupegrnutilit","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21356589,"name"=>"The North Face Borealis Classic backpack in blue","price"=>{"current"=>{"value"=>100.0,"text"=>"$100.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60160288,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1793248,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-classic-backpack-in-blue/prd/21356589?colourwayid=60160288","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-classic-backpack-in-blue/21356589-1-aviatornavytnfwhi","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21356855,"name"=>"The North Face Borealis Classic backpack in red","price"=>{"current"=>{"value"=>100.0,"text"=>"$100.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60160335,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1793272,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-classic-backpack-in-red/prd/21356855?colourwayid=60160335","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-classic-backpack-in-red/21356855-1-flareripstoptnfbl","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21356876,"name"=>"The North Face Borealis Classic backpack in gray","price"=>{"current"=>{"value"=>80.0,"text"=>"$80.00"},"previous"=>{"value"=>100.0,"text"=>"$100.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60160361,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1793269,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-classic-backpack-in-gray/prd/21356876?colourwayid=60160361","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-classic-backpack-in-gray/21356876-1-asphltgrylightningy","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21361266,"name"=>"The North Face Base Camp extra small duffel bag in blue","price"=>{"current"=>{"value"=>100.0,"text"=>"$100.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60160696,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1793680,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-extra-small-duffel-bag-in-blue/prd/21361266?colourwayid=60160696","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-extra-small-duffel-bag-in-blue/21361266-1-clearlakebluetnf","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21361282,"name"=>"The North Face Base Camp small duffel bag in orange","price"=>{"current"=>{"value"=>96.0,"text"=>"$96.00"},"previous"=>{"value"=>120.0,"text"=>"$120.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60160694,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1793690,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-small-duffel-bag-in-orange/prd/21361282?colourwayid=60160694","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-small-duffel-bag-in-orange/21361282-1-flaretnfblack","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21372664,"name"=>"The North Face Explore BLT small fanny pack in black","price"=>{"current"=>{"value"=>55.5,"text"=>"$55.50"},"previous"=>{"value"=>74.0,"text"=>"$74.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60161746,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1794848,"productType"=>"Product","url"=>"the-north-face/the-north-face-explore-blt-small-fanny-pack-in-black/prd/21372664?colourwayid=60161746","imageUrl"=>"http://images.asos-media.com/products/the-north-face-explore-blt-small-fanny-pack-in-black/21372664-1-tnfblacktnfwhite","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21372666,"name"=>"The North Face Base Camp tote bag in black","price"=>{"current"=>{"value"=>100.0,"text"=>"$100.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60161764,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1794832,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-tote-bag-in-black/prd/21372666?colourwayid=60161764","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-tote-bag-in-black/21372666-1-tnfblack","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21372685,"name"=>"The North Face Base Camp tote bag in gray/yellow","price"=>{"current"=>{"value"=>100.0,"text"=>"$100.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60161767,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1794835,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-tote-bag-in-gray-yellow/prd/21372685?colourwayid=60161767","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-tote-bag-in-gray-yellow/21372685-1-asphaltgreysummit","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21373255,"name"=>"The North Face Vault backpack in gray","price"=>{"current"=>{"value"=>80.0,"text"=>"$80.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60161814,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1794925,"productType"=>"Product","url"=>"the-north-face/the-north-face-vault-backpack-in-gray/prd/21373255?colourwayid=60161814","imageUrl"=>"http://images.asos-media.com/products/the-north-face-vault-backpack-in-gray/21373255-1-zincgrydrkhthrpersi","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21373637,"name"=>"The North Face Vault backpack in khaki camo","price"=>{"current"=>{"value"=>87.2,"text"=>"$87.20"},"previous"=>{"value"=>109.0,"text"=>"$109.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60161829,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1794929,"productType"=>"Product","url"=>"the-north-face/the-north-face-vault-backpack-in-khaki-camo/prd/21373637?colourwayid=60161829","imageUrl"=>"http://images.asos-media.com/products/the-north-face-vault-backpack-in-khaki-camo/21373637-1-hawthrnkhkdckcmptnw","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>14852203,"name"=>"Nike Training black gym drawstring bag","price"=>{"current"=>{"value"=>16.0,"text"=>"$16.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>16649077,"brandName"=>"Nike Training","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1674180,"productType"=>"Product","url"=>"nike-training/nike-training-black-gym-drawstring-bag/prd/14852203?colourwayid=16649077","imageUrl"=>"http://images.asos-media.com/products/nike-training-black-gym-drawstring-bag/14852203-1-black","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>20055112,"name"=>"Nike Hayward 2.0 backpack in navy","price"=>{"current"=>{"value"=>55.0,"text"=>"$55.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60004778,"brandName"=>"Nike","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1687936,"productType"=>"Product","url"=>"nike/nike-hayward-20-backpack-in-navy/prd/20055112?colourwayid=60004778","imageUrl"=>"http://images.asos-media.com/products/nike-hayward-20-backpack-in-navy/20055112-1-navy","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>14932599,"name"=>"The North Face Base Camp small duffel bag 50L in yellow","price"=>{"current"=>{"value"=>120.0,"text"=>"$120.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>16658013,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1680939,"productType"=>"Product","url"=>"the-north-face/the-north-face-base-camp-small-duffel-bag-50l-in-yellow/prd/14932599?colourwayid=16658013","imageUrl"=>"http://images.asos-media.com/products/the-north-face-base-camp-small-duffel-bag-50l-in-yellow/14932599-1-summitgoldtnfblac","videoUrl"=>"video.asos-media.com/products/the-north-face-base-camp-small-duffel-bag-50l-in-yellow/14932599-catwalk-AVS","isSellingFast"=>false},
      {"id"=>21315680,"name"=>"The North Face Cotton brown logo tote bag in natural","price"=>{"current"=>{"value"=>25.0,"text"=>"$25.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156502,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789654,"productType"=>"Product","url"=>"the-north-face/the-north-face-cotton-brown-logo-tote-bag-in-natural/prd/21315680?colourwayid=60156502","imageUrl"=>"http://images.asos-media.com/products/the-north-face-cotton-brown-logo-tote-bag-in-natural/21315680-1-weimaranerbrnlargelo","videoUrl"=>"video.asos-media.com/products/the-north-face-cotton-brown-logo-tote-bag-in-natural/21315680-catwalk-AVS","isSellingFast"=>false},
      {"id"=>21315683,"name"=>"The North Face Vault backpack in gray","price"=>{"current"=>{"value"=>47.2,"text"=>"$47.20"},"previous"=>{"value"=>59.0,"text"=>"$59.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156504,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789651,"productType"=>"Product","url"=>"the-north-face/the-north-face-vault-backpack-in-gray/prd/21315683?colourwayid=60156504","imageUrl"=>"http://images.asos-media.com/products/the-north-face-vault-backpack-in-gray/21315683-1-newtaupegrnutility","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21315688,"name"=>"The North Face Vault backpack in camo","price"=>{"current"=>{"value"=>59.0,"text"=>"$59.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156510,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789653,"productType"=>"Product","url"=>"the-north-face/the-north-face-vault-backpack-in-camo/prd/21315688?colourwayid=60156510","imageUrl"=>"http://images.asos-media.com/products/the-north-face-vault-backpack-in-camo/21315688-1-hawthrnkhkdckcmptnwt","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21315747,"name"=>"The North Face Jester backpack in black","price"=>{"current"=>{"value"=>69.0,"text"=>"$69.00"},"previous"=>{"value"=>"","text"=>""},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>false,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156551,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789672,"productType"=>"Product","url"=>"the-north-face/the-north-face-jester-backpack-in-black/prd/21315747?colourwayid=60156551","imageUrl"=>"http://images.asos-media.com/products/the-north-face-jester-backpack-in-black/21315747-1-tnfblack","videoUrl"=>"video.asos-media.com/products/the-north-face-jester-backpack-in-black/21315747-catwalk-AVS","isSellingFast"=>false},
      {"id"=>21315682,"name"=>"The North Face Borealis Backpack in Green","price"=>{"current"=>{"value"=>71.2,"text"=>"$71.20"},"previous"=>{"value"=>89.0,"text"=>"$89.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156505,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789658,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-backpack-in-green/prd/21315682?colourwayid=60156505","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-backpack-in-green/21315682-1-zincgrydarkheathreve","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21315690,"name"=>"The North Face Borealis backpack in dark gray","price"=>{"current"=>{"value"=>71.2,"text"=>"$71.20"},"previous"=>{"value"=>89.0,"text"=>"$89.00"},"rrp"=>{"value"=>"","text"=>""},"isMarkedDown"=>true,"isOutletPrice"=>false,"currency"=>"USD"},"colour"=>"","colourWayId"=>60156506,"brandName"=>"The North Face","hasVariantColours"=>false,"hasMultiplePrices"=>false,"groupId"=>"bags","productCode"=>1789657,"productType"=>"Product","url"=>"the-north-face/the-north-face-borealis-backpack-in-dark-gray/prd/21315690?colourwayid=60156506","imageUrl"=>"http://images.asos-media.com/products/the-north-face-borealis-backpack-in-dark-gray/21315690-1-zincgreydarkhthrtnfb","videoUrl"=>"","isSellingFast"=>false},
      {"id"=>21682632,"name"=>"Nike Advance crossbody bag in neon pink","price"=>{"current"=>{"value"=>30.0,"text"=>"$30.00"}}, "colour"=>"", "colourWayId"=>60187246, "brandName"=>"Nike", "hasVariantColours"=>false, "hasMultiplePrices"=>false, "groupId"=>"bags", "productCode"=>1819278, "productType"=>"Product", "url"=>"nike/nike-advance-crossbody-bag-in-neon-pink/prd/21682632?colourwayid=60187246", "imageUrl"=>"http://images.asos-media.com/products/nike-advance-crossbody-bag-in-neon-pink/21682632-1-neonpink", "videoUrl"=>"","isSellingFast"=>false}
    ]
    products_data.each_with_index do |product, index|
      Product.create!(brand: product["brandName"], 
        product_id: product["productCode"], 
        department: product["groupId"], 
        title: product["name"], 
        image_url: product["imageUrl"], 
        price: product["price"]["current"]["value"], 
        in_stock: true, 
        stock: prng.rand(2...100))
    end

## *****************************************************************************************************
##    USERS
##    2 Demo User Accounts along with 14 addition customers for fake orders
## *****************************************************************************************************
    User.create!(email:'admin@gmail.com', password:'1234', firstname: "#{Faker::Name.first_name}", lastname:"#{Faker::Name.last_name}",isStoreManager: true)
    User.create!(email:'customer@gmail.com', password:'1234', firstname: "#{Faker::Name.first_name}", lastname:"#{Faker::Name.last_name}", isStoreManager: false)
    14.times do |i|
      User.create!(email:"#{Faker::Internet.email}", password:'1234', firstname: "#{Faker::Name.first_name}", lastname:"#{Faker::Name.last_name}", isStoreManager: false)
    end

## *****************************************************************************************************
## ORDERS + ORDER_ITEMS
## *****************************************************************************************************
    24.times do |i|
      product1 = products[prng.rand(1...24)]
      product2 = products[prng.rand(25...47)]
      subtotal = (product1.price.to_f + product2.price.to_f).truncate(2) 
      total = subtotal.to_s
      order = Order.create!(
        user_id:"#{prng.rand(3...15)}", 
        total: total,
        item_count:2, 
        isShipped: true,
        paid: true,
        payment:"#{Faker::Stripe.valid_card(card_type: "visa_debit")}", 
        address_street:"#{Faker::Address.street_address}", 
        address_city:"#{Faker::Address.city}", 
        address_state:"#{Faker::Address.state_abbr}", 
        address_zip: "#{Faker::Address.zip}",
        date: "#{Faker::Date.between(from: 1.year.ago, to: 3.day.ago)}"
      )
      OrderItem.create!(order_id: order.id, title: product1.title, product_id: product1.id, qty: 1, price: product1.price, subtotal: product1.price)
      OrderItem.create!(order_id: order.id, title: product2.title, product_id: product2.id, qty: 1, price: product2.price, subtotal: product2.price)
    end

## *****************************************************************************************************
##    ORDERS FOR ADMIN USER
## *****************************************************************************************************
    4.times do |i|
      product1 = products[prng.rand(1...24)]
      product2 = products[prng.rand(25...47)]
      subtotal = (product1.price.to_f + product2.price.to_f).truncate(2) 
      total = subtotal.to_s
      order = Order.create!(
        user_id: 1, 
        total: total, 
        item_count:2, 
        isShipped: true,
        paid: true,
        payment:"#{Faker::Stripe.valid_card(card_type: "visa_debit")}", 
        address_street:"#{Faker::Address.street_address}", 
        address_city:"#{Faker::Address.city}", 
        address_state:"#{Faker::Address.state_abbr}", 
        address_zip: "#{Faker::Address.zip}",
        date: "#{Faker::Date.between(from: 1.year.ago, to: 3.day.ago)}"
      )
      OrderItem.create!(order_id: order.id, title: product1.title, product_id: product1.id, qty: 1, price: product1.price, subtotal: product1.price)
      OrderItem.create!(order_id: order.id, title: product2.title, product_id: product2.id, qty: 1, price: product2.price, subtotal: product2.price)
    end
  
## *****************************************************************************************************
##    ORDERS FOR DEMO CUSTOMER
## *****************************************************************************************************
    4.times do |i|
      product1 = products[prng.rand(1...24)]
      product2 = products[prng.rand(25...47)]
      subtotal = (product1.price.to_f + product2.price.to_f).truncate(2) 
      total = subtotal.to_s
      order = Order.create!(
        user_id: 2, 
        total: total, 
        item_count:2, 
        isShipped: false,
        paid: true,
        payment:"#{Faker::Stripe.valid_card(card_type: "visa_debit")}", 
        address_street:"#{Faker::Address.street_address}", 
        address_city:"#{Faker::Address.city}", 
        address_state:"#{Faker::Address.state_abbr}", 
        address_zip: "#{Faker::Address.zip}",
        date: "#{Faker::Date.between(from: 3.day.ago, to: 2.days.from_now)}"
      )
      OrderItem.create!(order_id: order.id, title: product1.title, product_id: product1.id, qty: 1, price: product1.price, subtotal: product1.price)
      OrderItem.create!(order_id: order.id, title: product2.title, product_id: product2.id, qty: 1, price: product2.price, subtotal: product2.price)
    end

## *****************************************************************************************************
##    REVIEWS & FAVORITES
## *****************************************************************************************************
    15.times do |i|
      y = i + 1
      product1 = products[prng.rand(1...10)]
      product2 = products[prng.rand(11...20)]
      product3 = products[prng.rand(21...30)]
      product4 = products[prng.rand(31...40)]
      product5 = products[prng.rand(41...47)]
      product6 = products[prng.rand(1...10)]
      product7 = products[prng.rand(11...20)]
      product8 = products[prng.rand(21...30)]
      product9 = products[prng.rand(31...40)]
      product10 = products[prng.rand(41...47)]

      Review.create!(user_id: y, product_id: product1.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product2.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product3.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product4.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product5.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product6.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product7.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product8.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product9.id, rating: "#{(prng.rand(1...10)).to_f/2}" )
      Review.create!(user_id: y, product_id: product10.id, rating: "#{(prng.rand(1...10)).to_f/2}" )

      Favorite.create!(user_id: y, product_id: prng.rand(1...10))
      Favorite.create!(user_id: y, product_id: prng.rand(11...20))
      Favorite.create!(user_id: y, product_id: prng.rand(21...30))
      Favorite.create!(user_id: y, product_id: prng.rand(31...40))
      Favorite.create!(user_id: y, product_id: prng.rand(41...47))
    end